### PR TITLE
perf: use stream methods from api

### PR DESCRIPTION
**Pull request by achingbrain**
Don't operate on whole buffers of files, instead use the stream methods from the files api.

Also updates deps and adds a bit of logging.

### CODE REVIEW

**Comment by diasdavid** [comment]
This repo needs CI, ping @ipfs-shipyard/dx

**Comment by achingbrain** [comment]
Interesting idea, it'd be good to benchmark them.

**Comment by diasdavid** [comment]
@dominictarr had some very good benchmarks comparing both. I'm not being able to find them right now but if I do, I'll forward it to you :)

**Comment by dominictarr** [comment]
there are some very mirco benchmarks in the pull-stream repo: https://github.com/pull-stream/pull-stream

There is also a simple benchmark for reading a large file in pull-file https://github.com/pull-stream/pull-file/blob/master/examples/bench.js I managed to get this faster than node streams with minimal effort, although when doing actual IO, because you are mostly waiting for IO to happen means that pull-streams probably doesn't make as much difference.

**Pull request merged**
